apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: deliveries
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: apideliveries-redis-store:6379
  - name: redisPassword
    value: ""
scopes:
  - apideliveries-app
