version: '3'
services:
  ############################
  # API Catalag
  ############################
  apicatalog-redis-store:
    image: "redis:alpine"
    ports:
      - "5101:6379"
    networks:
      - dapr-shop
  apicatalog-app:
    build:
      context: .
      dockerfile: ./src/ApiCatalog/Dockerfile
    ports:
      - "5001:80"      
      - "50001:50001"
    depends_on:
      - apicatalog-redis-store
    networks:
      - dapr-shop
  apicatalog-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "apicatalog-app",
     "-app-port", "80",     
     "-dapr-grpc-port", "50001",
     "-placement-host-address", "placement:50006",
     "-components-path", "/dapr/dev/components",
     "-config", "/dapr/dev/config.yaml"]
    volumes:
        - "./src/ApiCatalog/dapr/:/dapr"
    depends_on:
      - apicatalog-app
    network_mode: "service:apicatalog-app"
  ############################
  # Dapr deliveries
  ############################
  apideliveries-redis-store:
    image: "redis:alpine"
    ports:
      - "6101:6379"
    networks:
      - dapr-shop
  apideliveries-app:
    build:
      context: .
      dockerfile: ./src/ApiDeliveries/Dockerfile
    ports:
      - "6001:80"      
      - "50002:50001"
    depends_on:
      - apideliveries-redis-store
    networks:
      - dapr-shop
  apideliveries-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "apideliveries-app",
     "-app-port", "80",
     "-dapr-grpc-port", "50002",
     "-placement-host-address", "placement:50006",
     "-components-path", "/dapr/dev/components",
     "-config", "/dapr/dev/config.yaml"]
    volumes:
      - "./src/ApiDeliveries/dapr/:/dapr"
    depends_on:
      - apideliveries-app
    network_mode: "service:apideliveries-app"
  ############################
  # Dapr orders
  ############################
  apiorders-redis-queue:
    image: "redis:alpine"
    ports:
      - "7101:6379"
    networks:
      - dapr-shop
  apiorders-app:
    build:
      context: .
      dockerfile: ./src/ApiOrders/Dockerfile
    ports:
      - "7001:80"      
      - "50003:50001"
    depends_on:
      - apiorders-redis-store
    networks:
      - dapr-shop
  apiorders-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "apiorders-app",     
     "-app-port", "80",
     "-dapr-grpc-port", "50003",
     "-placement-host-address", "placement:50006",
     "-components-path", "/dapr/dev/components",
     "-config", "/dapr/dev/config.yaml"]
    volumes:
      - "./src/ApiOrders/dapr/:/dapr"
    depends_on:
      - apiorders-app
    network_mode: "service:apiorders-app"
  ############################
  # Dapr stocks
  ############################
  apistocks-redis-store:
    image: "redis:alpine"
    ports:
      - "8101:6379"
    networks:
      - dapr-shop
  apistocks-app:
    build:
      context: .
      dockerfile: ./src/ApiStocks/Dockerfile
    ports:
      - "8001:80"      
      - "50004:50001"
    depends_on:
      - apistocks-redis-store
    networks:
      - dapr-shop
  apistocks-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "apistocks-app",    
     "-app-port", "80",
     "-dapr-grpc-port", "50004",
     "-placement-host-address", "placement:50006",
     "-components-path", "/dapr/dev/components",
     "-config", "/dapr/dev/config.yaml"]
    volumes:
      - "./src/ApiStocks/dapr/:/dapr"
    depends_on:
      - apistocks-app
    network_mode: "service:apistocks-app"
  ############################
  # Dapr services
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - dapr-shop
  dashboard:
    image: "daprio/dashboard"
    ports:
      - "8080:8080"
    networks:
      - dapr-shop
  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"
    networks:
      - dapr-shop

networks:
    dapr-shop: