apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: catalog
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: apicatalog-redis-store:6379
  - name: redisPassword
    value: ""
scopes:
  - apicatalog-app
